openapi: 3.0.0
info:
  title: Hello World API
  description: A simple API that returns "Hello, World!" message.
  version: 1.0.0

servers:
  - url: https://34.8.238.109.nip.io
  - url: http://34.8.238.109.nip.io

paths:
  /:
    get:
      summary: Get Hello World message
      description: Responds with a "Hello, World!" message.
      responses:
        '200':
          description: Successful response
          content:
            text/plain:
              schema:
                type: string
                example: Hello, World!
