openapi: 3.0.0
info:
  title: Hello World API
  version: 1.0.0
  description: A simple API that returns a Hello World message
servers:
  - url: https://34.8.238.109.nip.io
  - url: http://34.8.238.109.nip.io
paths:
  /hello-world:
    get:
      summary: Returns a Hello World message
      operationId: getHelloWorld
      responses:
        '200':
          description: A successful response with Hello World message
          content:
            text/plain:
              schema:
                type: string
                example: Hello, World!
